version: '3.8'
services:
  #Reverse Proxy with NGINX
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
        - '${APP_PORT:-80}:80'
    volumes:
        - ./:/var/www
        - ./docker/nginx:/etc/nginx/conf.d
    networks:
        - frameworknet
  #PHP Service
  php:
    image: sergiodanilojr/php-dev
    container_name: php
    environment:
      - APP_ENV=${APP_ENV}
      - USER=${APP_USER}
      - PORT=9000
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - frameworknet

networks:
  frameworknet:
    driver: bridge
